/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstudioRouteImport } from './routes/_authenticated/estudio'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedInteligenciaRouteImport } from './routes/_authenticated/inteligencia'
import { Route as AuthenticatedMeuRadarRouteImport } from './routes/_authenticated/meu-radar'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPlanoRouteImport } from './routes/_authenticated/plano'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as ApiAiContentRouteImport } from './routes/api/ai-content'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as AuthenticatedProdutoIdRouteImport } from './routes/_authenticated/produto.$id'
import { Route as ApiAdminReadinessRouteImport } from './routes/api/admin/readiness'
import { Route as ApiAdminScraperRouteImport } from './routes/api/admin/scraper'
import { Route as ApiAdminSubscriptionsRouteImport } from './routes/api/admin/subscriptions'
import { Route as ApiBillingCancelRouteImport } from './routes/api/billing/cancel'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiBillingSyncRouteImport } from './routes/api/billing/sync'
import { Route as ApiIntegrationsProductsRouteImport } from './routes/api/integrations/products'
import { Route as ApiWebhooksMercadoPagoRouteImport } from './routes/api/webhooks/mercado-pago'
import { Route as ApiWebhooksPaypalRouteImport } from './routes/api/webhooks/paypal'
import { Route as ApiIntegrationsTiktokShopAuthorizeRouteImport } from './routes/api/integrations/tiktok-shop/authorize'
import { Route as ApiIntegrationsTiktokShopCallbackRouteImport } from './routes/api/integrations/tiktok-shop/callback'
import { Route as ApiIntegrationsTiktokShopDiscoveryRouteImport } from './routes/api/integrations/tiktok-shop/discovery'
import { Route as ApiIntegrationsTiktokShopShowcaseRouteImport } from './routes/api/integrations/tiktok-shop/showcase'
import { Route as ApiIntegrationsTiktokShopStatusRouteImport } from './routes/api/integrations/tiktok-shop/status'
import { Route as ApiIntegrationsTiktokShopTrackedRouteImport } from './routes/api/integrations/tiktok-shop/tracked'
import { Route as ApiIntegrationsTiktokShopShowcaseSyncRouteImport } from './routes/api/integrations/tiktok-shop/showcase/sync'
import { Route as ApiIntegrationsTiktokShopTrackedHistoryRouteImport } from './routes/api/integrations/tiktok-shop/tracked/history'
import { Route as ApiIntegrationsTiktokShopTrackedRefreshRouteImport } from './routes/api/integrations/tiktok-shop/tracked/refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudioRoute = AuthenticatedEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteligenciaRoute =
  AuthenticatedInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuRadarRoute = AuthenticatedMeuRadarRouteImport.update({
  id: '/meu-radar',
  path: '/meu-radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoRoute = AuthenticatedPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiContentRoute = ApiAiContentRouteImport.update({
  id: '/api/ai-content',
  path: '/api/ai-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutoIdRoute = AuthenticatedProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAdminReadinessRoute = ApiAdminReadinessRouteImport.update({
  id: '/api/admin/readiness',
  path: '/api/admin/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScraperRoute = ApiAdminScraperRouteImport.update({
  id: '/api/admin/scraper',
  path: '/api/admin/scraper',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscriptionsRoute = ApiAdminSubscriptionsRouteImport.update({
  id: '/api/admin/subscriptions',
  path: '/api/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCancelRoute = ApiBillingCancelRouteImport.update({
  id: '/api/billing/cancel',
  path: '/api/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSyncRoute = ApiBillingSyncRouteImport.update({
  id: '/api/billing/sync',
  path: '/api/billing/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsProductsRoute = ApiIntegrationsProductsRouteImport.update({
  id: '/api/integrations/products',
  path: '/api/integrations/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadoPagoRoute = ApiWebhooksMercadoPagoRouteImport.update({
  id: '/api/webhooks/mercado-pago',
  path: '/api/webhooks/mercado-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaypalRoute = ApiWebhooksPaypalRouteImport.update({
  id: '/api/webhooks/paypal',
  path: '/api/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsTiktokShopAuthorizeRoute =
  ApiIntegrationsTiktokShopAuthorizeRouteImport.update({
    id: '/api/integrations/tiktok-shop/authorize',
    path: '/api/integrations/tiktok-shop/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokShopCallbackRoute =
  ApiIntegrationsTiktokShopCallbackRouteImport.update({
    id: '/api/integrations/tiktok-shop/callback',
    path: '/api/integrations/tiktok-shop/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokShopDiscoveryRoute =
  ApiIntegrationsTiktokShopDiscoveryRouteImport.update({
    id: '/api/integrations/tiktok-shop/discovery',
    path: '/api/integrations/tiktok-shop/discovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokShopShowcaseRoute =
  ApiIntegrationsTiktokShopShowcaseRouteImport.update({
    id: '/api/integrations/tiktok-shop/showcase',
    path: '/api/integrations/tiktok-shop/showcase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokShopStatusRoute =
  ApiIntegrationsTiktokShopStatusRouteImport.update({
    id: '/api/integrations/tiktok-shop/status',
    path: '/api/integrations/tiktok-shop/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokShopTrackedRoute =
  ApiIntegrationsTiktokShopTrackedRouteImport.update({
    id: '/api/integrations/tiktok-shop/tracked',
    path: '/api/integrations/tiktok-shop/tracked',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsTiktokShopShowcaseSyncRoute =
  ApiIntegrationsTiktokShopShowcaseSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => ApiIntegrationsTiktokShopShowcaseRoute,
  } as any)
const ApiIntegrationsTiktokShopTrackedHistoryRoute =
  ApiIntegrationsTiktokShopTrackedHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiIntegrationsTiktokShopTrackedRoute,
  } as any)
const ApiIntegrationsTiktokShopTrackedRefreshRoute =
  ApiIntegrationsTiktokShopTrackedRefreshRouteImport.update({
    id: '/refresh',
    path: '/refresh',
    getParentRoute: () => ApiIntegrationsTiktokShopTrackedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/meu-radar': typeof AuthenticatedMeuRadarRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/api/ai-content': typeof ApiAiContentRoute
  '/api/health': typeof ApiHealthRoute
  '/api/usage': typeof ApiUsageRoute
  '/produto/$id': typeof AuthenticatedProdutoIdRoute
  '/api/admin/readiness': typeof ApiAdminReadinessRoute
  '/api/admin/scraper': typeof ApiAdminScraperRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/billing/cancel': typeof ApiBillingCancelRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/sync': typeof ApiBillingSyncRoute
  '/api/integrations/products': typeof ApiIntegrationsProductsRoute
  '/api/webhooks/mercado-pago': typeof ApiWebhooksMercadoPagoRoute
  '/api/webhooks/paypal': typeof ApiWebhooksPaypalRoute
  '/api/integrations/tiktok-shop/authorize': typeof ApiIntegrationsTiktokShopAuthorizeRoute
  '/api/integrations/tiktok-shop/callback': typeof ApiIntegrationsTiktokShopCallbackRoute
  '/api/integrations/tiktok-shop/discovery': typeof ApiIntegrationsTiktokShopDiscoveryRoute
  '/api/integrations/tiktok-shop/showcase': typeof ApiIntegrationsTiktokShopShowcaseRouteWithChildren
  '/api/integrations/tiktok-shop/status': typeof ApiIntegrationsTiktokShopStatusRoute
  '/api/integrations/tiktok-shop/tracked': typeof ApiIntegrationsTiktokShopTrackedRouteWithChildren
  '/api/integrations/tiktok-shop/showcase/sync': typeof ApiIntegrationsTiktokShopShowcaseSyncRoute
  '/api/integrations/tiktok-shop/tracked/history': typeof ApiIntegrationsTiktokShopTrackedHistoryRoute
  '/api/integrations/tiktok-shop/tracked/refresh': typeof ApiIntegrationsTiktokShopTrackedRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/meu-radar': typeof AuthenticatedMeuRadarRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/api/ai-content': typeof ApiAiContentRoute
  '/api/health': typeof ApiHealthRoute
  '/api/usage': typeof ApiUsageRoute
  '/produto/$id': typeof AuthenticatedProdutoIdRoute
  '/api/admin/readiness': typeof ApiAdminReadinessRoute
  '/api/admin/scraper': typeof ApiAdminScraperRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/billing/cancel': typeof ApiBillingCancelRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/sync': typeof ApiBillingSyncRoute
  '/api/integrations/products': typeof ApiIntegrationsProductsRoute
  '/api/webhooks/mercado-pago': typeof ApiWebhooksMercadoPagoRoute
  '/api/webhooks/paypal': typeof ApiWebhooksPaypalRoute
  '/api/integrations/tiktok-shop/authorize': typeof ApiIntegrationsTiktokShopAuthorizeRoute
  '/api/integrations/tiktok-shop/callback': typeof ApiIntegrationsTiktokShopCallbackRoute
  '/api/integrations/tiktok-shop/discovery': typeof ApiIntegrationsTiktokShopDiscoveryRoute
  '/api/integrations/tiktok-shop/showcase': typeof ApiIntegrationsTiktokShopShowcaseRouteWithChildren
  '/api/integrations/tiktok-shop/status': typeof ApiIntegrationsTiktokShopStatusRoute
  '/api/integrations/tiktok-shop/tracked': typeof ApiIntegrationsTiktokShopTrackedRouteWithChildren
  '/api/integrations/tiktok-shop/showcase/sync': typeof ApiIntegrationsTiktokShopShowcaseSyncRoute
  '/api/integrations/tiktok-shop/tracked/history': typeof ApiIntegrationsTiktokShopTrackedHistoryRoute
  '/api/integrations/tiktok-shop/tracked/refresh': typeof ApiIntegrationsTiktokShopTrackedRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/transparencia': typeof TransparenciaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estudio': typeof AuthenticatedEstudioRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/inteligencia': typeof AuthenticatedInteligenciaRoute
  '/_authenticated/meu-radar': typeof AuthenticatedMeuRadarRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/plano': typeof AuthenticatedPlanoRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/api/ai-content': typeof ApiAiContentRoute
  '/api/health': typeof ApiHealthRoute
  '/api/usage': typeof ApiUsageRoute
  '/_authenticated/produto/$id': typeof AuthenticatedProdutoIdRoute
  '/api/admin/readiness': typeof ApiAdminReadinessRoute
  '/api/admin/scraper': typeof ApiAdminScraperRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/billing/cancel': typeof ApiBillingCancelRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/sync': typeof ApiBillingSyncRoute
  '/api/integrations/products': typeof ApiIntegrationsProductsRoute
  '/api/webhooks/mercado-pago': typeof ApiWebhooksMercadoPagoRoute
  '/api/webhooks/paypal': typeof ApiWebhooksPaypalRoute
  '/api/integrations/tiktok-shop/authorize': typeof ApiIntegrationsTiktokShopAuthorizeRoute
  '/api/integrations/tiktok-shop/callback': typeof ApiIntegrationsTiktokShopCallbackRoute
  '/api/integrations/tiktok-shop/discovery': typeof ApiIntegrationsTiktokShopDiscoveryRoute
  '/api/integrations/tiktok-shop/showcase': typeof ApiIntegrationsTiktokShopShowcaseRouteWithChildren
  '/api/integrations/tiktok-shop/status': typeof ApiIntegrationsTiktokShopStatusRoute
  '/api/integrations/tiktok-shop/tracked': typeof ApiIntegrationsTiktokShopTrackedRouteWithChildren
  '/api/integrations/tiktok-shop/showcase/sync': typeof ApiIntegrationsTiktokShopShowcaseSyncRoute
  '/api/integrations/tiktok-shop/tracked/history': typeof ApiIntegrationsTiktokShopTrackedHistoryRoute
  '/api/integrations/tiktok-shop/tracked/refresh': typeof ApiIntegrationsTiktokShopTrackedRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/transparencia'
    | '/admin'
    | '/configuracoes'
    | '/dashboard'
    | '/estudio'
    | '/favoritos'
    | '/inteligencia'
    | '/meu-radar'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/radar'
    | '/api/ai-content'
    | '/api/health'
    | '/api/usage'
    | '/produto/$id'
    | '/api/admin/readiness'
    | '/api/admin/scraper'
    | '/api/admin/subscriptions'
    | '/api/billing/cancel'
    | '/api/billing/checkout'
    | '/api/billing/status'
    | '/api/billing/sync'
    | '/api/integrations/products'
    | '/api/webhooks/mercado-pago'
    | '/api/webhooks/paypal'
    | '/api/integrations/tiktok-shop/authorize'
    | '/api/integrations/tiktok-shop/callback'
    | '/api/integrations/tiktok-shop/discovery'
    | '/api/integrations/tiktok-shop/showcase'
    | '/api/integrations/tiktok-shop/status'
    | '/api/integrations/tiktok-shop/tracked'
    | '/api/integrations/tiktok-shop/showcase/sync'
    | '/api/integrations/tiktok-shop/tracked/history'
    | '/api/integrations/tiktok-shop/tracked/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/transparencia'
    | '/admin'
    | '/configuracoes'
    | '/dashboard'
    | '/estudio'
    | '/favoritos'
    | '/inteligencia'
    | '/meu-radar'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/radar'
    | '/api/ai-content'
    | '/api/health'
    | '/api/usage'
    | '/produto/$id'
    | '/api/admin/readiness'
    | '/api/admin/scraper'
    | '/api/admin/subscriptions'
    | '/api/billing/cancel'
    | '/api/billing/checkout'
    | '/api/billing/status'
    | '/api/billing/sync'
    | '/api/integrations/products'
    | '/api/webhooks/mercado-pago'
    | '/api/webhooks/paypal'
    | '/api/integrations/tiktok-shop/authorize'
    | '/api/integrations/tiktok-shop/callback'
    | '/api/integrations/tiktok-shop/discovery'
    | '/api/integrations/tiktok-shop/showcase'
    | '/api/integrations/tiktok-shop/status'
    | '/api/integrations/tiktok-shop/tracked'
    | '/api/integrations/tiktok-shop/showcase/sync'
    | '/api/integrations/tiktok-shop/tracked/history'
    | '/api/integrations/tiktok-shop/tracked/refresh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/transparencia'
    | '/_authenticated/admin'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/estudio'
    | '/_authenticated/favoritos'
    | '/_authenticated/inteligencia'
    | '/_authenticated/meu-radar'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/plano'
    | '/_authenticated/radar'
    | '/api/ai-content'
    | '/api/health'
    | '/api/usage'
    | '/_authenticated/produto/$id'
    | '/api/admin/readiness'
    | '/api/admin/scraper'
    | '/api/admin/subscriptions'
    | '/api/billing/cancel'
    | '/api/billing/checkout'
    | '/api/billing/status'
    | '/api/billing/sync'
    | '/api/integrations/products'
    | '/api/webhooks/mercado-pago'
    | '/api/webhooks/paypal'
    | '/api/integrations/tiktok-shop/authorize'
    | '/api/integrations/tiktok-shop/callback'
    | '/api/integrations/tiktok-shop/discovery'
    | '/api/integrations/tiktok-shop/showcase'
    | '/api/integrations/tiktok-shop/status'
    | '/api/integrations/tiktok-shop/tracked'
    | '/api/integrations/tiktok-shop/showcase/sync'
    | '/api/integrations/tiktok-shop/tracked/history'
    | '/api/integrations/tiktok-shop/tracked/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ApiAiContentRoute: typeof ApiAiContentRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiAdminReadinessRoute: typeof ApiAdminReadinessRoute
  ApiAdminScraperRoute: typeof ApiAdminScraperRoute
  ApiAdminSubscriptionsRoute: typeof ApiAdminSubscriptionsRoute
  ApiBillingCancelRoute: typeof ApiBillingCancelRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiBillingSyncRoute: typeof ApiBillingSyncRoute
  ApiIntegrationsProductsRoute: typeof ApiIntegrationsProductsRoute
  ApiWebhooksMercadoPagoRoute: typeof ApiWebhooksMercadoPagoRoute
  ApiWebhooksPaypalRoute: typeof ApiWebhooksPaypalRoute
  ApiIntegrationsTiktokShopAuthorizeRoute: typeof ApiIntegrationsTiktokShopAuthorizeRoute
  ApiIntegrationsTiktokShopCallbackRoute: typeof ApiIntegrationsTiktokShopCallbackRoute
  ApiIntegrationsTiktokShopDiscoveryRoute: typeof ApiIntegrationsTiktokShopDiscoveryRoute
  ApiIntegrationsTiktokShopShowcaseRoute: typeof ApiIntegrationsTiktokShopShowcaseRouteWithChildren
  ApiIntegrationsTiktokShopStatusRoute: typeof ApiIntegrationsTiktokShopStatusRoute
  ApiIntegrationsTiktokShopTrackedRoute: typeof ApiIntegrationsTiktokShopTrackedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudio': {
      id: '/_authenticated/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof AuthenticatedEstudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia': {
      id: '/_authenticated/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AuthenticatedInteligenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-radar': {
      id: '/_authenticated/meu-radar'
      path: '/meu-radar'
      fullPath: '/meu-radar'
      preLoaderRoute: typeof AuthenticatedMeuRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano': {
      id: '/_authenticated/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof AuthenticatedPlanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai-content': {
      id: '/api/ai-content'
      path: '/api/ai-content'
      fullPath: '/api/ai-content'
      preLoaderRoute: typeof ApiAiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produto/$id': {
      id: '/_authenticated/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof AuthenticatedProdutoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/admin/readiness': {
      id: '/api/admin/readiness'
      path: '/api/admin/readiness'
      fullPath: '/api/admin/readiness'
      preLoaderRoute: typeof ApiAdminReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scraper': {
      id: '/api/admin/scraper'
      path: '/api/admin/scraper'
      fullPath: '/api/admin/scraper'
      preLoaderRoute: typeof ApiAdminScraperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscriptions': {
      id: '/api/admin/subscriptions'
      path: '/api/admin/subscriptions'
      fullPath: '/api/admin/subscriptions'
      preLoaderRoute: typeof ApiAdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/cancel': {
      id: '/api/billing/cancel'
      path: '/api/billing/cancel'
      fullPath: '/api/billing/cancel'
      preLoaderRoute: typeof ApiBillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/sync': {
      id: '/api/billing/sync'
      path: '/api/billing/sync'
      fullPath: '/api/billing/sync'
      preLoaderRoute: typeof ApiBillingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/products': {
      id: '/api/integrations/products'
      path: '/api/integrations/products'
      fullPath: '/api/integrations/products'
      preLoaderRoute: typeof ApiIntegrationsProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercado-pago': {
      id: '/api/webhooks/mercado-pago'
      path: '/api/webhooks/mercado-pago'
      fullPath: '/api/webhooks/mercado-pago'
      preLoaderRoute: typeof ApiWebhooksMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paypal': {
      id: '/api/webhooks/paypal'
      path: '/api/webhooks/paypal'
      fullPath: '/api/webhooks/paypal'
      preLoaderRoute: typeof ApiWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/authorize': {
      id: '/api/integrations/tiktok-shop/authorize'
      path: '/api/integrations/tiktok-shop/authorize'
      fullPath: '/api/integrations/tiktok-shop/authorize'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/callback': {
      id: '/api/integrations/tiktok-shop/callback'
      path: '/api/integrations/tiktok-shop/callback'
      fullPath: '/api/integrations/tiktok-shop/callback'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/discovery': {
      id: '/api/integrations/tiktok-shop/discovery'
      path: '/api/integrations/tiktok-shop/discovery'
      fullPath: '/api/integrations/tiktok-shop/discovery'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/showcase': {
      id: '/api/integrations/tiktok-shop/showcase'
      path: '/api/integrations/tiktok-shop/showcase'
      fullPath: '/api/integrations/tiktok-shop/showcase'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/status': {
      id: '/api/integrations/tiktok-shop/status'
      path: '/api/integrations/tiktok-shop/status'
      fullPath: '/api/integrations/tiktok-shop/status'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/tracked': {
      id: '/api/integrations/tiktok-shop/tracked'
      path: '/api/integrations/tiktok-shop/tracked'
      fullPath: '/api/integrations/tiktok-shop/tracked'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopTrackedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/tiktok-shop/showcase/sync': {
      id: '/api/integrations/tiktok-shop/showcase/sync'
      path: '/sync'
      fullPath: '/api/integrations/tiktok-shop/showcase/sync'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopShowcaseSyncRouteImport
      parentRoute: typeof ApiIntegrationsTiktokShopShowcaseRoute
    }
    '/api/integrations/tiktok-shop/tracked/history': {
      id: '/api/integrations/tiktok-shop/tracked/history'
      path: '/history'
      fullPath: '/api/integrations/tiktok-shop/tracked/history'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopTrackedHistoryRouteImport
      parentRoute: typeof ApiIntegrationsTiktokShopTrackedRoute
    }
    '/api/integrations/tiktok-shop/tracked/refresh': {
      id: '/api/integrations/tiktok-shop/tracked/refresh'
      path: '/refresh'
      fullPath: '/api/integrations/tiktok-shop/tracked/refresh'
      preLoaderRoute: typeof ApiIntegrationsTiktokShopTrackedRefreshRouteImport
      parentRoute: typeof ApiIntegrationsTiktokShopTrackedRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstudioRoute: typeof AuthenticatedEstudioRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedInteligenciaRoute: typeof AuthenticatedInteligenciaRoute
  AuthenticatedMeuRadarRoute: typeof AuthenticatedMeuRadarRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanoRoute: typeof AuthenticatedPlanoRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedProdutoIdRoute: typeof AuthenticatedProdutoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstudioRoute: AuthenticatedEstudioRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedInteligenciaRoute: AuthenticatedInteligenciaRoute,
  AuthenticatedMeuRadarRoute: AuthenticatedMeuRadarRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanoRoute: AuthenticatedPlanoRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedProdutoIdRoute: AuthenticatedProdutoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiIntegrationsTiktokShopShowcaseRouteChildren {
  ApiIntegrationsTiktokShopShowcaseSyncRoute: typeof ApiIntegrationsTiktokShopShowcaseSyncRoute
}

const ApiIntegrationsTiktokShopShowcaseRouteChildren: ApiIntegrationsTiktokShopShowcaseRouteChildren =
  {
    ApiIntegrationsTiktokShopShowcaseSyncRoute:
      ApiIntegrationsTiktokShopShowcaseSyncRoute,
  }

const ApiIntegrationsTiktokShopShowcaseRouteWithChildren =
  ApiIntegrationsTiktokShopShowcaseRoute._addFileChildren(
    ApiIntegrationsTiktokShopShowcaseRouteChildren,
  )

interface ApiIntegrationsTiktokShopTrackedRouteChildren {
  ApiIntegrationsTiktokShopTrackedHistoryRoute: typeof ApiIntegrationsTiktokShopTrackedHistoryRoute
  ApiIntegrationsTiktokShopTrackedRefreshRoute: typeof ApiIntegrationsTiktokShopTrackedRefreshRoute
}

const ApiIntegrationsTiktokShopTrackedRouteChildren: ApiIntegrationsTiktokShopTrackedRouteChildren =
  {
    ApiIntegrationsTiktokShopTrackedHistoryRoute:
      ApiIntegrationsTiktokShopTrackedHistoryRoute,
    ApiIntegrationsTiktokShopTrackedRefreshRoute:
      ApiIntegrationsTiktokShopTrackedRefreshRoute,
  }

const ApiIntegrationsTiktokShopTrackedRouteWithChildren =
  ApiIntegrationsTiktokShopTrackedRoute._addFileChildren(
    ApiIntegrationsTiktokShopTrackedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  TransparenciaRoute: TransparenciaRoute,
  ApiAiContentRoute: ApiAiContentRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiAdminReadinessRoute: ApiAdminReadinessRoute,
  ApiAdminScraperRoute: ApiAdminScraperRoute,
  ApiAdminSubscriptionsRoute: ApiAdminSubscriptionsRoute,
  ApiBillingCancelRoute: ApiBillingCancelRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiBillingSyncRoute: ApiBillingSyncRoute,
  ApiIntegrationsProductsRoute: ApiIntegrationsProductsRoute,
  ApiWebhooksMercadoPagoRoute: ApiWebhooksMercadoPagoRoute,
  ApiWebhooksPaypalRoute: ApiWebhooksPaypalRoute,
  ApiIntegrationsTiktokShopAuthorizeRoute:
    ApiIntegrationsTiktokShopAuthorizeRoute,
  ApiIntegrationsTiktokShopCallbackRoute:
    ApiIntegrationsTiktokShopCallbackRoute,
  ApiIntegrationsTiktokShopDiscoveryRoute:
    ApiIntegrationsTiktokShopDiscoveryRoute,
  ApiIntegrationsTiktokShopShowcaseRoute:
    ApiIntegrationsTiktokShopShowcaseRouteWithChildren,
  ApiIntegrationsTiktokShopStatusRoute: ApiIntegrationsTiktokShopStatusRoute,
  ApiIntegrationsTiktokShopTrackedRoute:
    ApiIntegrationsTiktokShopTrackedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
